[package]
name = "evap_cooling"
version = "0.1.0"
edition = "2021"

[dependencies]
atomecs = {path = "../AtomECS"}
rand_distr = "0.4.0"
specs={ version="0.16.1", features=["rayon"] }
rand = "0.8.3"
nalgebra = { version = "0.18", features = ["serde-serialize"] }
